import PDFDocument from "pdfkit";
import fs from "node:fs";
import path from "node:path";
import type { SiteReport } from "../analyzer/analyzeSite.js";

const REPORTS_DIR = "reports";

// Palette
const COLOR = {
  dark: "#1A1A1A",
  gray: "#666666",
  brand: "#E08A00",
  green: "#1E9E5A",
  orange: "#E08A00",
  red: "#D23B3B",
  rule: "#E5E5E5",
} as const;

function getFileName(url: string): string {
  const slug = url
    .replace(/^https?:\/\//, "")
    .replace(/[^a-zA-Z0-9]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return `pulse-report-${slug || "site"}.pdf`;
}

function ratingWord(score: number): string {
  if (score >= 85) return "Ottimo";
  if (score >= 60) return "Buono";
  return "Critico";
}
function ratingColor(score: number): string {
  if (score >= 85) return COLOR.green;
  if (score >= 60) return COLOR.orange;
  return COLOR.red;
}
function priorityWord(score: number): string {
  if (score < 60) return "Alta priorità";
  if (score < 85) return "Media priorità";
  return "Bassa priorità";
}
function priorityColor(score: number): string {
  if (score < 60) return COLOR.red;
  if (score < 85) return COLOR.orange;
  return COLOR.green;
}

/**
 * Rimuove emoji e simboli non supportati dai font PDF standard (WinAnsi),
 * mantenendo lettere accentate, punteggiatura comune, trattini e bullet.
 */
function sanitize(text: string): string {
  return text
    .replace(
      /[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2190}-\u{21FF}\u{2300}-\u{23FF}\u{2B00}-\u{2BFF}\u{FE00}-\u{FE0F}\u{200D}]/gu,
      ""
    )
    .replace(/[ \t]{2,}/g, " ")
    .replace(/ +\n/g, "\n")
    .trim();
}

type Doc = InstanceType<typeof PDFDocument>;

function sectionTitle(doc: Doc, title: string): void {
  doc.moveDown(0.4);
  doc.font("Helvetica-Bold").fontSize(17).fillColor(COLOR.brand).text(title);
  const y = doc.y + 3;
  doc
    .strokeColor(COLOR.rule)
    .lineWidth(1)
    .moveTo(doc.page.margins.left, y)
    .lineTo(doc.page.width - doc.page.margins.right, y)
    .stroke();
  doc.moveDown(0.9);
  doc.font("Helvetica").fontSize(12).fillColor(COLOR.dark);
}

/** Riga "Label: 80/100  Buono" con il giudizio colorato. */
function metricLine(doc: Doc, label: string, score: number): void {
  doc.font("Helvetica").fontSize(12).fillColor(COLOR.dark).text(`${label}: ${score}/100   `, { continued: true });
  doc.font("Helvetica-Bold").fillColor(ratingColor(score)).text(ratingWord(score));
  doc.font("Helvetica").fillColor(COLOR.dark);
}

export async function generatePdfReport(
  data: SiteReport,
  aiReport: string,
  url: string
): Promise<string> {
  if (!url) throw new Error("URL mancante nel PDF generator");

  fs.mkdirSync(REPORTS_DIR, { recursive: true });
  const filePath = path.join(REPORTS_DIR, getFileName(url));

  return new Promise<string>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const stream = fs.createWriteStream(filePath);

    stream.on("finish", () => resolve(filePath));
    stream.on("error", reject);
    doc.on("error", reject);
    doc.pipe(stream);

    const left = doc.page.margins.left;
    const right = doc.page.width - doc.page.margins.right;

    // ── COVER ────────────────────────────────────────────────────────────────
    doc.moveDown(6);
    doc.font("Helvetica-Bold").fontSize(34).fillColor(COLOR.brand).text("PULSE", { align: "center" });
    doc.font("Helvetica").fontSize(16).fillColor(COLOR.gray).text("AUDIT REPORT", { align: "center", characterSpacing: 4 });
    doc.moveDown(1.5);

    const ruleY = doc.y;
    doc.strokeColor(COLOR.brand).lineWidth(2).moveTo(left + 120, ruleY).lineTo(right - 120, ruleY).stroke();
    doc.moveDown(1.5);

    doc.font("Helvetica-Bold").fontSize(15).fillColor(COLOR.dark).text(url, { align: "center" });
    doc.moveDown(0.5);
    doc.font("Helvetica").fontSize(11).fillColor(COLOR.gray)
      .text(`Generato il ${new Date().toLocaleString("it-IT")}`, { align: "center" });
    doc.text("Generated by Pulse AI Engine", { align: "center" });

    // ── EXECUTIVE SUMMARY ─────────────────────────────────────────────────────
    doc.addPage();
    const { avgSeo, avgPerformance: avgPerf, avgSecurity: avgSec } = data;
    const overall = Math.round((avgSeo + avgPerf + avgSec) / 3);

    sectionTitle(doc, "Executive Summary");
    metricLine(doc, "Overall", overall);
    doc.moveDown(0.3);
    metricLine(doc, "SEO", avgSeo);
    doc.moveDown(0.3);
    metricLine(doc, "Performance", avgPerf);
    doc.moveDown(0.3);
    metricLine(doc, "Security", avgSec);

    doc.moveDown(1);
    doc.font("Helvetica").fontSize(12).fillColor(COLOR.dark).text(
      overall >= 85
        ? "Sito con ottime prestazioni generali."
        : overall >= 60
        ? "Sito migliorabile con ottimizzazioni mirate."
        : "Criticità importanti rilevate."
    );

    if (data.technologies.length) {
      doc.moveDown(1.2);
      doc.font("Helvetica-Bold").fontSize(13).fillColor(COLOR.dark).text("Tecnologie rilevate");
      doc.moveDown(0.3);
      doc.font("Helvetica").fontSize(11).fillColor(COLOR.gray).text(data.technologies.join("  •  "));
    }

    // ── AI INSIGHTS ───────────────────────────────────────────────────────────
    doc.addPage();
    sectionTitle(doc, "AI Strategic Insights");
    doc.font("Helvetica").fontSize(11).fillColor(COLOR.dark)
      .text(sanitize(aiReport) || "Report AI non disponibile.", { align: "left", lineGap: 2 });

    // ── ACTION PLAN ───────────────────────────────────────────────────────────
    doc.addPage();
    sectionTitle(doc, "Action Plan");
    (
      [
        ["SEO", avgSeo],
        ["Performance", avgPerf],
        ["Security", avgSec],
      ] as const
    ).forEach(([name, score]) => {
      doc.font("Helvetica").fontSize(12).fillColor(COLOR.dark).text(`${name}: ${score}/100   `, { continued: true });
      doc.font("Helvetica-Bold").fillColor(priorityColor(score)).text(priorityWord(score));
      doc.font("Helvetica").fillColor(COLOR.dark);
      doc.moveDown(0.3);
    });

    const seoIssues = [...new Set(data.pages.flatMap((p) => p.seoIssues))];
    const secIssues = [...new Set(data.pages.flatMap((p) => p.securityIssues))];
    if (seoIssues.length || secIssues.length) {
      doc.moveDown(0.8);
      doc.font("Helvetica-Bold").fontSize(13).fillColor(COLOR.dark).text("Problemi ricorrenti");
      doc.moveDown(0.4);
      doc.font("Helvetica").fontSize(11).fillColor(COLOR.dark);
      [
        ...seoIssues.map((i) => `SEO — ${i}`),
        ...secIssues.map((i) => `Security — ${i}`),
      ].forEach((i) => doc.text(`•  ${i}`, { lineGap: 1 }));
    }

    // ── TECHNICAL OVERVIEW ────────────────────────────────────────────────────
    doc.addPage();
    sectionTitle(doc, "Technical Overview");
    doc.font("Helvetica").fontSize(10).fillColor(COLOR.dark);
    data.pages.slice(0, 10).forEach((p) => {
      doc.text(`${p.page}`, { continued: false });
      doc.fillColor(COLOR.gray).text(`   SEO ${p.seo}   ·   PERF ${p.performance}   ·   SEC ${p.security}`);
      doc.fillColor(COLOR.dark).moveDown(0.4);
    });

    doc.end();
  });
}
