import PDFDocument from "pdfkit";
import fs from "node:fs";
import path from "node:path";
import type { SiteReport } from "../analyzer/analyzeSite.js";

const REPORTS_DIR = "reports";

function getFileName(url: string): string {
  const slug = url
    .replace(/^https?:\/\//, "")
    .replace(/[^a-zA-Z0-9]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return `pulse-report-${slug || "site"}.pdf`;
}

function scoreLabel(score: number): string {
  if (score >= 85) return "🟢 Ottimo";
  if (score >= 60) return "🟠 Buono";
  return "🔴 Critico";
}

function priorityLabel(score: number): string {
  if (score < 60) return "🔴 Alta priorità";
  if (score < 85) return "🟠 Media priorità";
  return "🟢 Bassa priorità";
}

export async function generatePdfReport(
  data: SiteReport,
  aiReport: string,
  url: string
): Promise<string> {
  if (!url) throw new Error("URL mancante nel PDF generator");

  fs.mkdirSync(REPORTS_DIR, { recursive: true });
  const filePath = path.join(REPORTS_DIR, getFileName(url));

  return new Promise<string>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);

    stream.on("finish", () => resolve(filePath));
    stream.on("error", reject);
    doc.on("error", reject);
    doc.pipe(stream);

    // ── COVER ────────────────────────────────────────────────────────────────
    doc.fontSize(26).text("PULSE AUDIT REPORT", { align: "center" });
    doc.moveDown();
    doc.fontSize(14).text(url, { align: "center" });
    doc.moveDown(2);
    doc.fontSize(12).text(`Generato il ${new Date().toLocaleString("it-IT")}`, { align: "center" });
    doc.text("Generated by Pulse AI Engine", { align: "center" });

    // ── EXECUTIVE SUMMARY ─────────────────────────────────────────────────────
    doc.addPage();
    const { avgSeo, avgPerformance: avgPerf, avgSecurity: avgSec } = data;
    const overall = Math.round((avgSeo + avgPerf + avgSec) / 3);

    doc.fontSize(20).text("EXECUTIVE SUMMARY");
    doc.moveDown();
    doc.fontSize(12);
    doc.text(`Overall: ${overall} → ${scoreLabel(overall)}`);
    doc.text(`SEO: ${avgSeo} → ${scoreLabel(avgSeo)}`);
    doc.text(`Performance: ${avgPerf} → ${scoreLabel(avgPerf)}`);
    doc.text(`Security: ${avgSec} → ${scoreLabel(avgSec)}`);
    doc.moveDown();
    doc.text(
      overall >= 85
        ? "Sito con ottime prestazioni generali."
        : overall >= 60
        ? "Sito migliorabile con ottimizzazioni mirate."
        : "Criticità importanti rilevate."
    );

    if (data.technologies.length) {
      doc.moveDown();
      doc.fontSize(13).text("Tecnologie rilevate");
      doc.fontSize(11).text(data.technologies.join(", "));
    }

    // ── AI INSIGHTS ───────────────────────────────────────────────────────────
    doc.addPage();
    doc.fontSize(20).text("AI STRATEGIC INSIGHTS");
    doc.moveDown();
    doc.fontSize(11).text(aiReport || "Report AI non disponibile.");

    // ── ACTION PLAN (priorità per area) ───────────────────────────────────────
    doc.addPage();
    doc.fontSize(20).text("ACTION PLAN");
    doc.moveDown();
    doc.fontSize(12);
    (
      [
        ["SEO", avgSeo],
        ["Performance", avgPerf],
        ["Security", avgSec],
      ] as const
    ).forEach(([name, score]) => {
      doc.text(`• ${name}: ${score}/100 → ${priorityLabel(score)}`);
    });

    const seoIssues = [...new Set(data.pages.flatMap((p) => p.seoIssues))];
    const secIssues = [...new Set(data.pages.flatMap((p) => p.securityIssues))];
    if (seoIssues.length || secIssues.length) {
      doc.moveDown();
      doc.fontSize(14).text("Problemi ricorrenti");
      doc.moveDown(0.5);
      doc.fontSize(11);
      [
        ...seoIssues.map((i) => `SEO — ${i}`),
        ...secIssues.map((i) => `Security — ${i}`),
      ].forEach((i) => doc.text(`• ${i}`));
    }

    // ── TECHNICAL OVERVIEW ────────────────────────────────────────────────────
    doc.addPage();
    doc.fontSize(20).text("TECHNICAL OVERVIEW");
    doc.moveDown();
    doc.fontSize(10);
    data.pages.slice(0, 10).forEach((p) => {
      doc.text(`${p.page}  |  SEO ${p.seo}  ·  PERF ${p.performance}  ·  SEC ${p.security}`);
    });

    doc.end();
  });
}
